class "Action"

function Action:Call(trigger, owner, other)
end
--[[
activate-special-action
alter-absolute-cash-action
alter-absolute-location-action
alter-age-action
alter-base-type-action
alter-cloak-action
alter-condition-true-yet-action
alter-damage-action
alter-energy-action
alter-hidden-action
alter-location-action
alter-max-velocity-action
alter-occupation-action
alter-offline-action
alter-owner-action
alter-special-action
alter-spin-action
alter-thrust-action
alter-velocity-action
assume-initial-object-action
change-score-action
color-flash-action
computer-select-action
create-object-action
create-object-set-dest-action
declare-winner-action
die-action
disable-keys-action
display-message-action
enable-keys-action
land-at-action
make-sparks-action
nil-target-action
no-action
play-sound-action
set-destination-action
set-zoom-action
--]]