--[[
autopilot-condition
counter-condition
counter-greater-condition
current-computer-condition
current-message-condition
destruction-condition
direct-is-subject-target-condition
distance-greater-condition
half-health-condition
is-auxiliary-object-condition
is-target-object-condition
no-condition
no-ships-left-condition
not-autopilot-condition
object-is-being-built-condition
owner-condition
proximity-condition
subject-is-player-condition
time-condition
velocity-less-than-equal-to-condition
zoom-level-condition
--]]