key_menu = { { "Ship",
				{ key = "KP8", name = "Accelerate" },
				{ key = "KP5", name = "Decelerate" }, 
				{ key = "KP4", name = "Turn Counter-Clockwise" }, 
				{ key = "KP6", name = "Turn Clockwise" }, 
				{ key = "MaltL", key_display = "AltL", name = "Fire Weapon 1" }, 
				{ key = "MctrlL", key_display = "CtrlL", name = "Fire Weapon 2" }, 
				{ key = " ", key_display = "Space", name = "Fire/Activate Special" }, 
				{ key = "Tab", name = "Warp" } },
			{ "Command", 
				{ key = "pgdn", name = "Select Friendly" }, 
				{ key = "KPequals", key_display = "KP=", name = "Select Hostile" }, 
				{ key = "KPdivide", key_display = "KP/", name = "Select Base" }, 
				{ key = "MshiftL", key_display = "ShiftL", name = "Target" }, 
				{ key = "MaltL", key_display = "AltL", name = "Move Order" }, 
				{ key = "KPplus", key_display = "KP+", name = "Scale In" }, 
				{ key = "KPminus", key_display = "KP-", name = "Scale Out" }, 
				{ key = "up", key_display = "UP", name = "Computer Previous" }, 
				{ key = "down", key_display = "DOWN", name = "Computer Next" }, 
				{ key = "right", key_display = "RGHT", name = "Computer Accept/Select/Do" }, 
				{ key = "left", key_display = "LEFT", name = "Computer Cancel/Back Up" } },
			{ "Shortcuts",
				{ key = "F8", name = "Transfer Control" }, 
				{ key = "F9", name = "Zoom to 1:1" }, 
				{ key = "F10", name = "Zoom to 1:2" }, 
				{ key = "F11", name = "Zoom to 1:4" }, 
				{ key = "F12", name = "Zoom to 1:16" }, 
				{ key = "ins", name = "Zoom to Closest Hostile" }, 
				{ key = "home", name = "Zoom to Closest Object" }, 
				{ key = "pgup", name = "Zoom to All" }, 
				{ key = "del", name = "Message Next Page / Clear" } },
			{ "Utility",
				{ key = "F1", name = "Help" }, 
				{ key = "F2", name = "Lower Volume" }, 
				{ key = "F3", name = "Raise Volume" }, 
				{ key = "F4", name = "Mute Music" }, 
				{ key = "F5", name = "Expert Net Settings" }, 
				{ key = "F6", name = "Fast Motion" } }, 
			{ "HotKeys",
				{ key = "1", name = "HotKey 1" }, 
				{ key = "2", name = "HotKey 2" }, 
				{ key = "3", name = "HotKey 3" }, 
				{ key = "4", name = "HotKey 4" }, 
				{ key = "5", name = "HotKey 5" }, 
				{ key = "6", name = "HotKey 6" }, 
				{ key = "7", name = "HotKey 7" }, 
				{ key = "8", name = "HotKey 8" }, 
				{ key = "9", name = "HotKey 9" }, 
				{ key = "0", name = "HotKey 10" } } }
