-- Preload all sounds
sound.preload("11.snd-1")
sound.preload("11.snd-2")
sound.preload("22")
sound.preload("22.snd-1")
sound.preload("22.snd-2")
sound.preload("22.snd-3")
sound.preload("22.snd-4")
sound.preload("22.snd-5")
sound.preload("22.snd")
sound.preload("Astrocrunch")
sound.preload("Beam Scan Modified")
sound.preload("Beep Buzzer copy.22")
sound.preload("ComboBeep")
sound.preload("ExplosionCombo")
sound.preload("Flack1Short")
sound.preload("Flack2Short")
sound.preload("ISpaceWoosh")
sound.preload("ITeletype")
sound.preload("Lectro Zap Mixed Low")
sound.preload("Lectro Zap Mixed")
sound.preload("Let's Go")
sound.preload("NaughtyBeep")
sound.preload("RocketLaunch")
sound.preload("RocketLaunchr")
sound.preload("SShot 1")
sound.preload("ShotC")
sound.preload("Spark Thump")
sound.preload("Stealth Off")
sound.preload("Stealth On")
sound.preload("Stingy Whip Laser Misc")
sound.preload("Thonk Warp 1.2")
sound.preload("Thonk Warp 1.3")
sound.preload("Warp1")
sound.preload("Warp2")
sound.preload("Warp3")
sound.preload("Warp4")
sound.preload("WarpIn")
sound.preload("WarpOut")
sound.preload("ZoomChange")
sound.preload("audem missile 1")
sound.preload("audemedon destroyer")
sound.preload("audemedon missile 2")
sound.preload("explosn.02 short")
sound.preload("fighter launch")
sound.preload("gaitori destroyer")
sound.preload("heavy destroyer (cantharan).8")
sound.preload("human destroyer")
sound.preload("human laser 2")
sound.preload("human laser 3")
sound.preload("human torpedo 1")
sound.preload("human torpedo 2")
sound.preload("jumpgate opens hifi copy")
sound.preload("laser, elejeetian sound 2")
sound.preload("missile, elejeetian sound 1")
sound.preload("missile, elejeetian sound 3")
sound.preload("pop")
sound.preload("salril destroyer")
sound.preload("space blob sucks")
sound.preload("target deactivate beep.snd")
sound.preload("target drone laser")
sound.preload("thonk warp 1.1")
sound.preload("thonk warp 1.4")
-- graphics.preload_font("prototype")
-- graphics.preload_font("sneakout")
graphics.preload_image("Bootloader/Ares")
graphics.preload_image("Bootloader/Xsera")
graphics.preload_image("Panels/AmbrosiaLogo")
graphics.preload_image("Panels/BrainpenLogo")
graphics.preload_image("Panels/MainBottom")
graphics.preload_image("Panels/MainTop")
graphics.preload_image("Panels/MainLeft")
graphics.preload_image("Panels/MainRight")
graphics.preload_image("Panels/NLCredits")
graphics.preload_image("Panels/PanelBottom")
graphics.preload_image("Panels/PanelLeft")
graphics.preload_image("Panels/PanelRight")
graphics.preload_image("Panels/PanelTop")
graphics.preload_image("Panels/SideLeft")
graphics.preload_image("Panels/SideLeftTrans")
graphics.preload_image("Panels/SideRight")
graphics.preload_image("Panels/SideRightTrans")
graphics.preload_image("Panels/XseraLogo")
graphics.preload_sprite_sheet("Explosions/BestExplosion")
graphics.preload_sprite_sheet("Explosions/MikeExplosion")
graphics.preload_sprite_sheet("Explosions/MissileExplosion")
graphics.preload_sprite_sheet("Explosions/StrangeExplosion")
graphics.preload_sprite_sheet("Explosions/SuperNova")
graphics.preload_sprite_sheet("Weapons/AquaPulse")
graphics.preload_sprite_sheet("Weapons/AquaRingPulse")
graphics.preload_sprite_sheet("Weapons/AudemedonMissile")
graphics.preload_sprite_sheet("Weapons/BlueBullet")
graphics.preload_sprite_sheet("Weapons/Fireball")
graphics.preload_sprite_sheet("Weapons/FlackExplosion")
graphics.preload_sprite_sheet("Weapons/GreenPhoton")
graphics.preload_sprite_sheet("Weapons/GreenTorpedo")
graphics.preload_sprite_sheet("Weapons/Gunfire")
graphics.preload_sprite_sheet("Weapons/IndigoPulse")
graphics.preload_sprite_sheet("Weapons/NewShots")
graphics.preload_sprite_sheet("Weapons/PulseBlue")
graphics.preload_sprite_sheet("Weapons/PulseOrange")
graphics.preload_sprite_sheet("Weapons/PurpleTorpedo")
graphics.preload_sprite_sheet("Weapons/RedPulse")
graphics.preload_sprite_sheet("Weapons/RedPulseMike")
graphics.preload_sprite_sheet("Weapons/TwinOrbitShot")
graphics.preload_sprite_sheet("Weapons/YellowPhoton")
graphics.preload_sprite_sheet("Weapons/YellowSparkleShot")
graphics.preload_sprite_sheet("Weapons/Special/cMissile")
